### ISSUE TITLE
프론트 일관성 설정

### ISSUE THREAD

**Issue by sd8599** [DohoonHan/D-OH#161]
## 하진의 작업 목록
- [x] 헤더: 컨테스트 상세 페이지에서 충돌 해결
- [x]  메인 페이지: 이미지 수정
 - [x] contest/application/detail: noimg 추가
 - [x] #162
 - [x] users/contest: 다음 버튼 마진 조정, 아이콘(“어떤 작품이 필요하세요?”) 수정
- [x]  users/contest/budget: 등수 text 크기 조정, 마진 조정
 - [x] users/contest/payment: 전체 wid 맞추기, 버튼 수정, 아이콘(“어떤 작품이 필요하세요?”) 수정
 - [x] users/login: 로그인 문구 추가
 - [x] users/mypage: 표 사이 간격 조정, 목록 보기 ‘x’ -> ‘목록’으로 변경 (border만 두고 나머지 제거), 버튼 색상 변경, radius 제거, bottom border 제거 (맨 아래)
 - [x] users/contest/award? : 전체적으로 수정

## 차차의 작업 목록
 - [x] 콘테스트 리스트: Bootstrap 링크 레이아웃에 맞춰 수정
 - [x] 컨테스트 상세 페이지: wid 줄이기
 - [x] 이벤트 페이지: 이벤트 이름 키우기, 마진 조정, 버튼 내리기
 - [x] 이벤트 상세 페이지: 크기 맞추기, 버튼 디자인 공지사항과 맞추기
 - [x] 이벤트 등록 페이지: 버튼 변경, 배경색 공지사항과 동일하게 맞추기
 - [x] 공지사항 & 임시저장: 전체적으로 간격 추가, 상세 페이지 크기 키우기 (최소 높이 설정)
 - [x] users/mypage/profile/edit: 마진 조정, input 높이 조정, 버튼 색상 변경
 - [x]  채팅버튼위치&색상변경

## 공통 작업 항목
* 버튼 색상
- [ ] 기본 배경색: 회색 또는 검정색 (#212529, 단일 버튼일 경우)
- [ ] Hover 시: 검정색(#333) 또는 회색일 경우

* 버튼 로직 참고

.button {
    display: inline-block;
    width: auto;
    padding: 8px 20px; /* 수정된 패딩 */
    color: #fff; /* 텍스트 색상을 흰색으로 설정 */
    text-align: center;
    text-decoration: none;
    margin-top: 20px;
    border-radius: 6px; /* 수정된 border-radius */
    transition: background-color 0.3s ease-in-out; /* transform, box-shadow 제거 */
    font-weight: 600;
    cursor: pointer; /* 커서 스타일 추가 */
}

/* 목록으로 버튼 */
.button-list {
    background-color: #212529; /* 배경색을 검정색으로 설정 */
}

.button-list:hover {
    background-color: #333; /* hover 시 배경색 변경 */
    text-decoration: none;
    color: white;
}

/* 참여하기 버튼 */
.button-participate {
    background-color: #d3d3d3; /* 밝은 회색으로 설정 */
    color: black; /* 텍스트 색상을 검정색으로 설정 */
}

.button-participate:hover {
    text-decoration: none;
    background-color: #b3b3b3; /* hover 시 좀 더 어두운 회색으로 변경 */
    color: white; /* hover 시 텍스트 색상 유지 */
}

* 버튼 디자인
- [x] Radius: 6px
- [x] Padding: 8px & 20px
- [x] 그림자 제거
- [x] 반응 효과 제거
- [x] 커서 모양 적용

* 게시글
- [x] 기본 배경색: 검정색
- [x] Text 색상: 흰색
- [x] 체크박스 추가

**Comment by sooyoonhee** [comment]
#162 : 수정사항 기록하려다 issue 생성되어 issue 닫음
앞의 이미지가 없을 경우, noimg 설정 이미 되어 있음
